version: '3.8'

services:
  # Django Service
  web:
    build: .
    container_name: django_app
    command: gunicorn --bind 0.0.0.0:8000 Trading.wsgi:application
    working_dir: /app/Trading
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  # Redis Service
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  # Celery Worker
  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_worker
    working_dir: /app/Trading
    command: celery -A Trading worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
    restart: always

  # Celery Beat (if using periodic tasks)
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_beat
    working_dir: /app/Trading
    command: celery -A Trading beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
    restart: always
